apiVersion: v1
kind: Namespace
metadata:
  name: nfs-provisioner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-client-provisioner
  namespace: nfs-provisioner
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nfs-client-provisioner-runner
rules:
- apiGroups: [""]
  resources: ["nodes","persistentvolumes","endpoints","pods","secrets","services","events","persistentvolumeclaims"]
  verbs: ["get","list","watch","create","delete","patch","update"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get","list","watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-nfs-client-provisioner
subjects:
- kind: ServiceAccount
  name: nfs-client-provisioner
  namespace: nfs-provisioner
roleRef:
  kind: ClusterRole
  name: nfs-client-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  namespace: nfs-provisioner
spec:
  replicas: 1
  selector:
    matchLabels: { app: nfs-client-provisioner }
  template:
    metadata:
      labels: { app: nfs-client-provisioner }
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
      - name: nfs-client-provisioner
        image: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
        env:
        - name: PROVISIONER_NAME
          value: nfs.csi.k8s.io/subdir
        - name: NFS_SERVER
          value: "172.23.200.194"
        - name: NFS_PATH
          value: "/home/nfs-kubernetes"
        volumeMounts:
        - name: nfs-client-root
          mountPath: /persistentvolumes
      volumes:
      - name: nfs-client-root
        nfs:
          server: 172.23.200.194
          path: /home/nfs-kubernetes
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-rwx
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"   # jadikan default (opsional)
provisioner: nfs.csi.k8s.io/subdir
parameters:
  # folder otomatis: <namespace>/<nama-pvc>
  pathPattern: "${.PVC.namespace}/${.PVC.name}"
  onDelete: retain                         # data tetap saat PVC dihapus
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
